### ISSUE TITLE
fields set at 0 require to delete the 0 to enter a value

### ISSUE THREAD

**Issue by murbard** [murbard/ctez#12]
A tester reports:

"When you go to deposit, withdraw etc there is already the number 0 in the field and you have to delete it before you type your input, it's a small thing but it can get annoying when you forget "

**Comment by shekhar-shubhendu** [comment]
I am really not sure how this can be handled.
Clearing the input on click will fix this but that might be annoying to someone who just wants to add a decimal maybe.

**Comment by murbard** [comment]
not a common use case to "just want add a decimal"

**Comment by shekhar-shubhendu** [comment]
i have removed all zeroes in #15
