### ISSUE TITLE
pairing with kukai should bring up kukai's edo2net wallet

### ISSUE THREAD

**Issue by murbard** [murbard/ctez#13]
which is at https://edonet.kukai.app/

**Comment by tezit** [comment]
the beacon DAppClient contructor you should set an explicit preferredNetwork of edonet, the default is mainnet so currently if you select Kukai it sends you to mainnet Kukai

preferredNetwork: NetworkType.EDONET should be added to the contructor options when an app is for testing on edonet, note that this can't be overriden by requests once ininitalized, the network setting during requests must match it

**Comment by shekhar-shubhendu** [comment]
yes, this should be fixed by taquito/beacon and can not be handled by the FE.

**Comment by murbard** [comment]
https://github.com/ecadlabs/taquito/issues/753

**Comment by shekhar-shubhendu** [comment]
resolved in #15
