### ISSUE TITLE
Info display

### ISSUE THREAD

**Issue by murbard** [murbard/ctez#3]
On all pages, the following information should be displayed (not necessarily all in one place, the account specific information might make sense when clicking on the cat in the upper right, the rest might make sense as part of a header)

- [x] current target: target / 2^48
- [x] current price implied by the CFMM: cash_pool / token_pool
- [x] premium over target in %: (price / target - 1)
- [x] current annual drift in %: (1 + drift / 2^48)^(365.25 * 24 * 3600) - 1
- [x] annual drift over the past week in %: (target_now / (target_7_days_ago))^52.1786 - 1
- [x] tez in my account (the one linked through beacon)
- [x] ctez in my account (the one linked through beacon)

On the oven page:

- [x] total tez in ovens
- [x] total ctez outstanding

On each oven:

- [x] how many ctez can be minted in that oven
- [x] warning sign when it is one month away from being liquidated: (assume the target grows at the current drift for a month, and if that would liquidate the account, mark the oven in red or something)

On the cfmm page

- [x] total liquidity in the cfmm (expressed in tez, just double the cash_pool value)

When using the CFMM

- [x] instead of displaying fields like min_bought_tokens etc, express as max_slippage. That means, compute the limits based on the current values of cash_pool and token_pool, then add max_slippage % to that to determine the parameter to pass to the contract
- [x] when adding liquidity, instead of max_ctez, express it as slippage as well, instead of min_lqt express it
as a min % of the pool that will be owned : min_lqt / (total_lqt  + min_lqt)

------

Historical graphs for target, cfmm price, premium, drift (with smoothing) would all be very neat but they require a middleware and aren't as important as the above.

**Comment by murbard** [comment]
To work out an example: 

Suppose you are calling `cash_to_token`. You need to pass to the contract `minTokensBought` and specify the amount of tez you're passing. Instead, let the user enter "tez to pay" (`cashSold`), and slippage (in percentage, e.g. 0.5%).

Then compute `minTokensBought` as follow:

`min_tokens_bought = cashSold * 997 * tokenPool / (cashPool * 1000 + cashShold * 997) * (1 - slippage)`

the first part, `cashSold * 997 * tokenPool / (cashPool * 1000 + cashShold * 997)` is how much you'd be getting if the order went in right away, the second part `1 - slippage` accounts for the fact that maybe it'll get a little worse than that and gives you a margin of error.

You then display `cashSold * 997 * tokenPool / (cashPool * 1000 + cashShold * 997)` as a preview to the user.

Timeout should also be expressed as a relative offset to the current time (e.g. 20 minutes)

**Comment by murbard** [comment]
- [x] Display "tez in ovens", "outstanding" tez in the cat menu, not as cards
- [x] Consolidate the information into a single card, not one card per value
- [x] In buy or sell, it's "tez to ctez" and "ctez to tez", not "XTZ to Ctez" and "Ctez to XTZ".
- [x] in whithdaw, "Amount (in ctez)" not "Amount"
- [x] in mint and repay, "Amount (in ctez)" not "Amount"
- [x] Main logo on top left should be ctez not tez
- [x] Use the ꜩ character when showing the liquidity (or some image with the same size / style as the text, using the big svg logo is confusing in this instance, but it's OK in input boxes)
- [x] do not display all the information everywhere, some information belongs on the oven page, some on the cfmm page, see original issue

**Comment by murbard** [comment]
- [x] display remaining mintable ctez and max mintable ctez in the mint window and the repay panels not on the oven card. 
- [x] Display outstanding ctez on both the card and the mint and repay panels
- [x] Display utilization on the card as a percentage with two decimals (outstanding_ctez / max_mintable_ctez)
- [x] Clicking on the logo takes you to the oven page which is good, but the pointer should be a hand to indicate that it's clickable

**Comment by murbard** [comment]
Formula for an oven being once month away from liquidation

ctez_outstanding * (target/2^48)^((1 + drift/2^48) * 365.25 * 24 * 3600/12) * 16 / 15 > tez_balance

**Comment by shekhar-shubhendu** [comment]
remaining parts addressed in #15

**Comment by shekhar-shubhendu** [comment]
> Formula for an oven being once month away from liquidation
> 
> ctez_outstanding * (target/2^48)^((1 + drift/2^48) * 365.25 * 24 * 3600/12) * 16 / 15 > tez_balance

is oven is safe then there is a green circle around the avatar else it is red

![image](https://user-images.githubusercontent.com/9253059/113258026-b05f8b00-92cb-11eb-908b-26654da9dd66.png)

**Comment by murbard** [comment]
Make it less subtle, maybe the entire card background is light red, and an  ⚠️ emoji by the utilization

**Comment by murbard** [comment]
Also, the same formula should be used to limit what the UI will let you mint (you could mint more by calling the contract directly, but the UI won't let you mint more than what would put you in the red)

**Comment by shekhar-shubhendu** [comment]
> Also, the same formula should be used to limit what the UI will let you mint (you could mint more by calling the contract directly, but the UI won't let you mint more than what would put you in the red)

Yes. This will be part of #6
